import { type RouteConfig, route, index, layout } from "@react-router/dev/routes";

export default [index("routes/home.tsx"),
  // route("our-services", "./routes/our-services.tsx"),
  // route("eating-disorders", "./routes/eating-disorders.tsx"),
  // route("personality-disorders", "./routes/personality-disorders.tsx"),
  // route("body-image-dysmorphic-disorder", "./routes/body-dysmorphic-disorder.tsx"),
  // route("trauma-and-dissociation-disorder", "./routes/trauma-and-dissociation-disorder.tsx"),
  // route("drugs-and-substance-addiction", "./routes/drugs-and-substance-addiction.tsx"),
  // route("internal-family-systems-therapy", "./routes/internal-family-systems-therapy.tsx"),
  // route("post-traumatic-stress-disorder-ptsd", "./routes/post-traumatic-stress-disorder.tsx"),
  // route("sex-addiction", "./routes/sex-addiction.tsx"),
  // route("gambling", "./routes/gambling-addiction.tsx"),
  // route("bullying-disorder", "./routes/bullying-disorder.tsx"),
  // route("alcoholism", "./routes/alcoholism-addiction.tsx"),
  // route("self-harm", "./routes/self-harm.tsx"),
  // route("sexual-abuse-disorder", "./routes/sexual-abuse-disorder.tsx"),
  // route("suicide-ideation-disorder", "./routes/suicide-ideation-disorder.tsx"),
  // route("obsessive-compulsive-personality-disorder-ocpd", "./routes/obsessive-compulsive-personality-disorder.tsx"),
  // route("military-and-first-responders", "./routes/military-and-first-responders.tsx"),
  // route("contact", "./routes/contact.tsx"),
  // route("blog", "./routes/blog.tsx"),
  // route("blog/:id", "./routes/blog-post.tsx"),
] satisfies RouteConfig;
